### PR TITLE
make: initial support for meson build system

### PR DESCRIPTION
**Pull request by xbjfk**
The meson build system is a build system with many advantages over others, and one I consider to be the best. It is one of the fastest build systems, has an easy to understand, and extensible syntax (for example a target can be defined to automatically build docs). It supports all platforms the other build systems do (Linux, Windows, FreeBSD) and is easy to use when cross compiling via a cross file (such as with MingW). It can also programmatically generate the version, instead of needing to edit a header file every time. On my Linux system, meson (configure) took 0.65s and ninja (build) took 16.62s, while the make-based build system took 30.22s.
See https://mesonbuild.com/Overview.html and https://mesonbuild.com/Comparisons.html for me info on the meson build system.
Meson requires all subprojects to be in the subprojects directory. It unfortunately does not support symlinks in the subprojects directory, so I updated existing submodules to be symlinks to submodules in the subprojects directory. See https://github.com/mesonbuild/meson/issues/8827 for more info.
Meson also natively supports CMake subprojects (such as wingetopt) and supports configurable options, such as whether TCG should be used or if the system's libc is musl.
Note: existing build systems can still be used.

[#2]

Merge AFTER Seagate/opensea-common#3, Seagate/opensea-transport#8 and Seagate/opensea-operations#4

-----
[View rendered BUILDING.md](https://github.com/xbjfk/openSeaChest/blob/develop/BUILDING.md)
[View rendered BUILDING_OLD.md](https://github.com/xbjfk/openSeaChest/blob/develop/BUILDING_OLD.md)

### CODE REVIEW

**Comment by vonericsen** [comment]
Hi @xbjfk, 

Thanks for this contribution! This looks really cool!
We will review it, but it will take some time to go through it and check out how meson works.
Thanks for preserving the existing makefiles since we have other internal tools that use those for now 😄

**Comment by vonericsen** [comment]
After playing around with meson for a bit in both Windows and Linux, overall I like it.

There are a few things I would like to figure out before accepting this so that we can continue supporting it and migrate to it permanently.
I have seen that there is a way to use cross-compilation, so I would like to spend time testing this for at least Aarch64 in Linux and Windows as we have had to send out tools for this architecture internally and it has seen a growing number of requests recently (at least in Linux).

The other thing I have started to play around with, but have not quite figured out how to do yet, is setting the "Run as administrator" in the Windows version of the tool...you would not believe how many times I have had to answer questions about running tools as admin prior to enforcing this in the embedded manifest file. I think I am close since the manifest is generated, but not pulled into the final link yet. I believe I have to figure out specifying a path to the manifest, then that will be figured out for MSVC compiles.

Once I get these figured out and check with my team on their thoughts, we will likely accept this pull request and run with it.

**Comment by vonericsen** [comment]
meson will be a great addition to openSeaChest.
Thanks @xbjfk!

**Comment by eli-schwartz** [comment]
> The other thing I have started to play around with, but have not quite figured out how to do yet, is setting the "Run as administrator" in the Windows version of the tool...you would not believe how many times I have had to answer questions about running tools as admin prior to enforcing this in the embedded manifest file. I think I am close since the manifest is generated, but not pulled into the final link yet. I believe I have to figure out specifying a path to the manifest, then that will be figured out for MSVC compiles.

If you have a manifest already (I did a very cursory look in this repo, didn't see one) you should be able to link it into the executable by adding a `.rc` file as a source.

Meson provides a windows module for processing rc files: https://mesonbuild.com/Windows-module.html
Hopefully this does everything you need.

**Comment by vonericsen** [comment]
@eli-schwartz,
Thanks for the information!
We don't have a manifest for openSeaChest, but the visual studio project file options set the manifest file options in the linker to set the "require administrator" there, so that is what I was looking into.
I was able to pass the same linker options with some modifications in the meson build file, but was not sure whether that was a good way to solve this problem or not. I decided to accept this pull request anyways since I thought it was plenty close for now and didn't want to hang it up on this one detail since this seemed like it wouldn't be too far off from working.
I will take a look at the link you gave to work on adding it in the future 😄

**Comment by eli-schwartz** [comment]
Great, happy to help.

(I am always happy to help people more effectively use Meson.)

...


Microsoft's general documentation on manifest files seems to be https://docs.microsoft.com/en-us/cpp/build/how-to-embed-a-manifest-inside-a-c-cpp-application?view=msvc-170 and suggests using a post-build step which edits the binary in place, which is of course less than completely desirable from meson's perspective (two rules cannot build the same file). I think Visual Studio may do some sort of black magic behind the scenes by generating a temporary manifest, so maybe there is some option there to save that file and view the results?

**Comment by vonericsen** [comment]
Between that link and [this one](https://docs.microsoft.com/en-us/cpp/build/reference/manifest-tool-property-pages?view=msvc-170), I think it's close.

I added the following and it will generate a manifest file with the exe outputs in Windows (visual studio only, not sure what to do for mingw if anything):
`add_project_link_arguments('/MANIFEST', language : 'c')`
`add_project_link_arguments('/MANIFESTUAC:\"level=\'requireAdministrator\' uiAccess=\'false\'"', language : 'c')`

Looking at the visual studio linking options, it also adds
`/ManifestFile:"x64\Static-Release\OpenSeaChest_Sample.exe.intermediate.manifest"`
This seems to only specify the intermediate file name, which does not seem necessary right now.
At this point this seems to have the exe and manifest files, so I think a post step to call `mt.exe` will cause it to embed it.

I tried manually running `mt.exe` to do this and it fails with an error (c1010070)...and I have not found any helpful solutions online. I don't have spaces in the path, which seems to be the common issue, so no idea what is wrong.
If there is a way to put this into an `.rc` file instead and use the Windows module you mentioned earlier, that will probably be easier to make happen right now with this other unknown error occuring.

**Comment by eli-schwartz** [comment]
An example resource file could be seen here:

https://github.com/python/cpython/blob/main/PC/python_exe.rc
https://github.com/python/cpython/blob/main/PC/python.manifest

**Comment by xbjfk** [comment]
I took a shot at this in #65, works with MingW on Windows (and Linux cross compile) and MSVC and Clang on Windows.

**Comment by vonericsen** [comment]
Thanks for all the help!
I merged #65 as it worked correctly when I gave it a test. I was going to attempt that exact same thing today but you beat me to it! 😄

**Pull request merged**
